name = "hanwen-school-worker"
compatibility_date = "2025-05-10"
account_id = "d5138aae215d7b432c81f3e46945696c"
main = "worker.js"  # 指定入口文件

kv_namespaces = [
  { binding = "KV", id = "your-kv-namespace-id" }  # 替换为真实ID
]

[vars]
SITE_NAME = "翰文学校育才分校"
SITE_DOMAIN = "school.moujie.dpdns.org"